version: '3.8'
services:
  book_manager:
    container_name: book_manager
    build: .
    ports:
      - 3001:3001
    env_file:
      - .env
    networks:
      - book_manager_net
    volumes:
      - type: bind
        source: .
        target: /bookManager
    depends_on:
      - db
    restart: on-failure
  db:
    container_name: book_manager_db
    image: "postgres:15.2-alpine"
    env_file:
      - .env
    volumes:
      - book_manager_db:/var/lib/postgresql/data/
    networks:
      - book_manager_net
volumes:
  book_manager_db:
networks:
  book_manager_net:
    
    